apiVersion: v2
name: testkube
description: A Helm chart for testkube.
type: application
version: 1.4.30
dependencies:
  - name: testkube-operator
    version: 1.4.3
    #repository: https://kubeshop.github.io/helm-charts
    repository: "file://../testkube-operator"
  - name: mongodb
    condition: mongodb.enabled
    version: 13.0.0
    repository: https://charts.bitnami.com/bitnami
  - name: testkube-api
    version: 1.4.21
    #repository: https://kubeshop.github.io/helm-charts
    repository: "file://../testkube-api"
  - name: testkube-dashboard
    version: 1.4.5
    #repository: https://kubeshop.github.io/helm-charts
    repository: "file://../testkube-dashboard"
    condition: testkube-dashboard.enabled
