# For local development and debugging:
# - just uncomment local repositories definitions 
# - and comment out repositories with remote urls.
# - then just run `helm dep up ./testkube/charts/testkube`
# - once there were any changes to update and re-build local helm charts and its dependencies.
apiVersion: v2
name: testkube
description: A Helm chart for testkube.
type: application
version: 0.5.60
dependencies:
- name: testkube-operator
  version: 0.5.8
  repository: https://kubeshop.github.io/helm-charts
  #repository: "file://../../../testkube-operator/charts/testkube-operator"
- name: mongodb
  version: 10.0.0
  repository: https://charts.bitnami.com/bitnami
- name: api-server
  version: 0.5.15
  repository: https://kubeshop.github.io/helm-charts
  #repository: "file://../../../api-server/charts/api-server"
- name: postman-executor
  version: 0.5.15
  repository: https://kubeshop.github.io/helm-charts
  #repository: "file://../../../postman-executor/charts/postman-executor"
  condition: postman-executor.enabled
- name: cypress-executor
  version: 0.5.11
  repository: https://kubeshop.github.io/helm-charts
  #repository: "file://../../../cypress-executor/charts/cypress-executor"
  condition: cypress-executor.enabled
- name: curl-executor
  version: 0.5.12
  repository: https://kubeshop.github.io/helm-charts
  #repository: "file://../../../curl-executor/charts/curl-executor"
  condition: curl-executor.enabled
- name: testkube-dashboard
  version: 0.5.0
  repository: https://kubeshop.github.io/helm-charts
  #repository: "file://../../../testkube-dashboard/charts/testkube-dashboard"
  condition: testkube-dashboard.enabled
