name: Refresh GitHib Pages.

on:
  push:
    paths:
      - 'postman-executor/**'
      - 'cypress-executor/**'
      - 'api-server/**'
      - 'kubtest-operator/**'
      - 'kubtest/**'
    branches:
      - main

  pull_request:
    paths:
      - 'cypress-executor/**'
      - 'postman-executor/**'
      - 'api-server/**'
      - 'kubtest-operator/**'
      - 'kubtest/**'
    branches:
      - main

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/kubeshop/helm-charts/pages/builds \
            --header "Authorization: Bearer $USER_TOKEN"
        env:
          # You must create a personal token with repo access as GitHub does
          # not yet support server-to-server page builds.
          USER_TOKEN: ${{ secrets.USER_TOKEN }}